### ISSUE TITLE
State of this repo after Goodreads API discontinuation

### ISSUE THREAD

**Issue by CalvinWu4** [kylekarpack/react-goodreads-shelf#13]
Am I correct in guessing this repo will no longer be usable after that?

**Comment by kylekarpack** [comment]
I believe this is correct. If you don't already have an API key, it appears that Goodreads is no longer issuing new ones. I don't see a definite date for the API to be discontinued, but it does seem like Goodreads may [indefinitely support existing API usage](https://help.goodreads.com/s/article/Does-Goodreads-support-the-use-of-APIs):
> we continue to support active API users who meet our terms of service
That said, I'll keep an eye on any developments and try to get out updates if they're needed

**Comment by eligundry** [comment]
@kylekarpack I saw this announcement the other day and decided to take it into my own hands and I think I have a decent solution. I use this on my personal site and I have another module that uses [CORS Anywhere](https://cors-anywhere.herokuapp.com/) to screen scrape Github for a contribution graph. I went ahead and mocked up a React hook to fetch this data and pull the data from HTML using similar logic.

https://github.com/eligundry/eligundry.com/blob/master/gatsby/src/components/Reading/useGoodreads.ts

I'd be happy to port this approach to this library if interested.

**Comment by kylekarpack** [comment]
Hi @eligundry, looks like we work on a lot of similar things! I have a [React GitHub Graph](https://github.com/kylekarpack/react-github-graph) repo that uses CORS Anywhere as well.

That `useGoodreads` hook approach is pretty clever! If you're able to submit a PR, I'd love to incorporate it. It's definitely brittle, but probably no more brittle than the GoodReads API from here on out 😬. We'll probably need to drop a few options like `sort`,  `limit`, and whatever else isn't supported by query string parameters there. Let me know what you think!

**Comment by eligundry** [comment]
I need to figure out why it times out, but I will work on it this weekend probably.

**Comment by kylekarpack** [comment]
I think CORS Anywhere might be down at the moment

**Comment by kylekarpack** [comment]
Alright, I've added the scraping functionality to this component (bulk of the work is here: https://github.com/kylekarpack/react-goodreads-shelf/blob/master/src/hooks/useGoodreadsShelf.js). Basically, it works by switching to scraping mode if an API key is not provided. I'm going to test a little more and then I'll release another version of the package if everything looks good.

**Comment by eligundry** [comment]
I dunno if you have tried this on iOS, but it's super unreliable and I'm not certain if it's an error or CORS Anywhere being slammed. I'm about to self host a CORS Anywhere instance so I can track it down.

**Comment by kylekarpack** [comment]
I think it's almost certainly some flakiness in CORS Anywhere. It was definitely down a few hours ago, but looks fine on iOS to me now. Definitely open to some other ideas if you have any, since CORS Anywhere certainly isn't a production-level service.
