### ISSUE TITLE
Doesn't work with SSG

### ISSUE THREAD

**Issue by alexkreidler** [kylekarpack/react-goodreads-shelf#63]
I have a Vite app using [`vite-plugin-ssr`](https://vite-plugin-ssr.com/) to enable static site generation/server-side pre-rendering. I tried using the component but it doesn't render on server-only pages because [useEffect doesn't render on server-only renders](https://codewithhugo.com/react-useeffect-ssr/). I looked into the codebase to see if I could split out the data fetching part to go into the data fetching function of the framework (e.g. `onBeforeRender` in `vite-plugin-ssr` or`getStaticProps` in NextJS), but because the library uses DOM APIs to parse an HTML table returned from Goodreads because they depracated their API, this would be non-trivial to convert to server code.

It might be a good idea to add a note to the README so people are aware if they try making a static site with Next or Vite. Thanks for this cool library!

**Comment by kylekarpack** [comment]
Thanks for the report. I'll see if I can figure out a reasonable way to make this render server-side, or add a note to the readme if not.

**Comment by kylekarpack** [comment]
@alexkreidler, are you able to provide some help setting up a repro case for this? I created a new `vite-plugin-ssr` [application](https://github.com/kylekarpack/react-goodreads-shelf/blob/ssr/ssr/pages/index/index.page.tsx#L9) and [enabled SSR and prerendering](https://github.com/kylekarpack/react-goodreads-shelf/blob/ssr/ssr/vite.config.ts#L6).

From what I can tell, it doesn't fail and does prerender the basic shell of the plugin when building. It certainly doesn't render the entire component though, so could you briefly clarify if that's what you're looking for? I am not super up-to-date on SSG, so any help pointing me in the right direction to get started would be appreciated. Thanks!

**Comment by alexkreidler** [comment]
My site uses the [HTML only](https://vite-plugin-ssr.com/render-modes#html-only) option, which instead of bundling React JS code, turns the site into static HTML (potentially with islands of interactivity). It is enabled by renaming `.page.tsx` to `.page.server.tsx`, so committed to the `ssr` branch in my fork of this repo with those changes. Then when doing `npm run dev` or `npm run build & serve dist/client` I simply see an empty page, without the loading bar or any books, and an empty `.rgs-shelf` element:

![image](https://github.com/kylekarpack/react-goodreads-shelf/assets/11166947/899b835c-c080-497d-ab00-fdc3433cebc6)


![image](https://github.com/kylekarpack/react-goodreads-shelf/assets/11166947/06c36e79-286e-4a4e-9d5c-2541a9438461)

It makes sense that vite-plugin-ssr wouldn't run the entire component lifecycle/hooks to render static HTML. It might also be rare that people use frameworks with settings like these. But one way to support it could be to split the data fetching into another function that could run in the server-side NodeJS process, and making the React component simply a pure function of the input books data. To make it run in Node though you'd probably need a DOM implementation like JSDOM and it might be slightly involved to make sure that works. I'm happy to close this issue in that case. Thanks for taking a look!

**Comment by kylekarpack** [comment]
Very helpful, thanks! I'll take a look and see what I can dig up

**Comment by kylekarpack** [comment]
Hi @alexkreidler, I just released version `4.0.0-beta` [on npm](https://www.npmjs.com/package/react-goodreads-shelf/v/4.0.0-beta). I don't think it will solve all the SSG issues, but it does remove the need for DOM parsing, so I think it's a big step in the right direction. I'll take a look at splitting up the fetching and rendering next - I think that's a great idea.

**Comment by kylekarpack** [comment]
Hi @alexkreidler, I dropped another version that should be fully SSG-compatible! It's available [on NPM](https://www.npmjs.com/package/react-goodreads-shelf/v/4.0.0-beta.2).

There are some examples avaiable [in the SSR testing package](https://github.com/kylekarpack/react-goodreads-shelf/tree/v4/packages/example-ssr/pages/index) that I made. I'm going to continue to run some tests and clean up a little more. Please let me know if you have any input regarding the API before I release this out of beta.

**Comment by alexkreidler** [comment]
Wow, awesome! I do really like the API, it's very ergonomic and I'm glad the example with vite works. Also I noticed you are [using Rust](https://github.com/kylekarpack/react-goodreads-shelf-api/blob/main/rust/src/lib.rs) for a [cloudflare workers API](https://github.com/kylekarpack/react-goodreads-shelf/blob/v4/packages/react-goodreads-shelf/src/util/get-url.ts#LL5C24-L5C84): `https://react-goodreads-shelf.kylekarpack.workers.dev/users/63515611`

Very cool!

**Comment by kylekarpack** [comment]
The existing worker is written in NodeJS, and I just moved it [into this repo.](https://github.com/kylekarpack/react-goodreads-shelf/blob/v4/packages/api/src/worker.ts). I don't think Cloudflare workers supports their nifty `HTMLRewriter` in Rust, so it might be stuck in NodeJS for a while, since fully parsing the Goodreads response eats a lot of CPU clock, even in Rust.

I'll try to remember to shoot you a note when I release a full 4.0.0 version! Hopefully in the upcoming weeks.
